source 'https://rubygems.org'
source 'https://gem.fury.io/engineerai'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.6'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'dotenv-rails'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_posts-3dc5b993', '0.0.12', require: 'bx_block_posts'
gem 'bx_block_payments', '0.1.3'
gem 'bx_block_photo_library-6419d914', '0.0.2', require: 'bx_block_photo_library'
gem 'bx_block_scheduling-d1f08754', '0.0.2', require: 'bx_block_scheduling'
gem 'bx_block_login-3d0582b5', '0.0.10', require: 'bx_block_login'
gem 'bx_block_forgot_password-4de8968b', '0.0.6', require: 'bx_block_forgot_password'
gem 'account_block', '0.0.29'
gem 'bx_block_push_notifications-c0f9e9b7', '0.0.10', require: 'bx_block_push_notifications'
gem 'bx_block_appointment_management-eb816fd3', '0.0.7', require: 'bx_block_appointment_management'
gem 'bx_block_shopping_cart-9ec30a1c', '0.0.10', require: 'bx_block_shopping_cart'
gem 'bx_block_order_management-674a3e38', '0.0.7', require: 'bx_block_order_management'
gem 'bx_block_admin', '0.0.12'
gem 'bx_block_catalogue-0e5da613', '0.0.8', require: 'bx_block_catalogue'
gem 'bx_block_roles_permissions-c50949d0', '0.0.6', require: 'bx_block_roles_permissions'
gem 'bx_block_settings-5412d427', '0.0.3', require: 'bx_block_settings'
gem 'bx_block_upload_media-9de56634', '0.0.2', require: 'bx_block_upload_media'
gem 'bx_block_filter_items-b1be1f37', '0.0.2', require: 'bx_block_filter_items'
gem 'bx_block_video_library', '0.0.3'
gem 'bx_block_custom_ads-e8d68990', '0.0.2', require: 'bx_block_custom_ads'
gem 'bx_block_notifications-a22eb801', '0.0.5', require: 'bx_block_notifications'
gem 'bx_block_phone_verification', '0.0.2'
gem 'bx_block_trending', '0.1.1', require: 'bx_block_trending'
gem 'bx_block_activity_feed', '0.0.5', require: 'bx_block_activity_feed'
gem 'bx_block_categories-acd0763f', '0.0.9', require: 'bx_block_categories'
gem 'bx_block_location-99004202', '0.0.4', require: 'bx_block_location'
gem 'bx_block_reviews', '0.0.2', require: 'bx_block_reviews'
gem 'bx_block_contact_us-6e0a750f', '0.0.3', require: 'bx_block_contact_us'
gem 'bx_block_help_centre', '0.0.2'
gem 'bx_block_promo_codes', '0.0.3', require: 'bx_block_promo_codes'
gem 'bx_block_custom_user_subs', '0.0.9'
gem 'bx_block_visual_analytics', '0.1.1'
gem 'bx_block_payment_admin', '0.0.2'
gem 'builder_base', '0.0.45'
gem 'sassc-rails'
gem 'activeadmin'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'
gem 'bx_block_cors'
gem 'rack-cors'
