# Default values for app-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# For Custom CNAME configuration refer docs first: https://builderai.quip.com/S1SiA9110Eph/Using-Custom-CNAME

replicaCount: 2

PodDisruptionBudget:
  minAvailable: "50%"

# Specify additional values that will be presented as environment variables to the pod.
appExtConfig:
  SMTP_ADDRESS: "smtp.develmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "WE4CX23WXDSU33WDOAAEWAK6JU"
  RAILS_ENV: "production"
  RAILS_LOG_TO_STDOUT: "true"
  REDIS_URL : "redis://redis-master.redis.svc.cluster.local"
  DOMAIN_URL : "https://meril-101378-ruby.b101378.dev.eastus.az.svc.builder.cafe/"
  # A change to RAILS_MAX_THREADS might affect the 
  # resource limits set below so that needs to be taken into consideration.
  RAILS_MAX_THREADS: "10"

image:
  repository:  gitlab.builder.ai:5000/template-app
  pullPolicy: IfNotPresent
  tag: 8.8.8

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

probes:
  livenessProbe:
    initialDelaySeconds: 40
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 40
    periodSeconds: 20

probesSidekiq:
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
  readinessProbe:
    initialDelaySeconds: 120
    periodSeconds: 20

railsMigration:
  enabled: true
  timeout: 300
  retry: 2
  command:
    - bundle
    - exec
    - rails
    - db:migrate
    - db:seed


railsSidekiq:
  enabled: false
  replicaCount: 1
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
  autoscaling:
    enabled: false
    minReplicas: 1
    # maxReplicas must not exceed the max node count
    maxReplicas: 3
    targetCPU: 50
    targetMemory: 80 

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

# The following values are based on RAILS_MAX_THREADS: "10" in appExtConfig above
# If one of them is changed, the other might need changing too
resources:
  limits:
    cpu: 350m
    memory: 515Mi
  requests:
    cpu: 350m
    memory: 315Mi

sidekiqResources:
  limits:
    cpu: 350m
    memory: 515Mi
  requests:
    cpu: 350m
    memory: 315Mi

# Enable the kubernetes horizontal pod autoscaler for this application
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 3
  targetCPU: 50
  targetMemory: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

annotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '3000'

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    # nginx.ingress.kubernetes.io/server-alias: <custom_cname>
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: rrapp.local
      paths: ['/']
  tls:
    - secretName: https-cert
      hosts:
        - rrapp.local
        # - <custom_cname>

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - app-deploy
            topologyKey: "kubernetes.io/hostname"


affinitySidekiq:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: "app.kubernetes.io/name"
                  operator: In
                  values:
                  - app-deploySidekiq
            topologyKey: "kubernetes.io/hostname"
