appExtConfig:
    SMTP_PASSWORD: ENC[AES256_GCM,data:iPTAyky3FtOE8K3LybrHrULtQ1ISVXKC2RM=,iv:37I/YOdg2OrlaSGw6G4jQSX+XJ4rxNSX914JmhjJPjg=,tag:h3uPP64LFTvbQrHH1x5d1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-05-31T10:15:14Z'
    mac: ENC[AES256_GCM,data:cn9L5QppE8S7BsQr2gIcnSdOfbHfy4KsrZIfm8FTM+JC1qLqH6wzUqoZ72y6tb/gyGGrVeTrBICjltedq8qRKuRXWDlqn8c3PUJJKiU/ziC4wZFfT4i9NL+9Osd9ex/4Azz/MnHq53nCBedEnh4iFa3KafEhrAYkL3v9+9Mq6sQ=,iv:EaFam5dHI721Wpz1Fk/IS1wiwAtrxH2TkD6ydH8yCjo=,tag:z1MiRna9er3YHnt2dkGSlA==,type:str]
    pgp:
    -   created_at: '2021-05-31T10:14:25Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA1gSLZ947okQAQgAlVxJ4YVyBiMFNMEsA3t3Vj5vOBatAX6NcQbmian+ysGd
            ZHhkuPouA7xKEI24fSZQp5ZumKzg/7DLlg/Rh2LtQCze+eRDeBI77E8WMYjuCzKS
            J7odtT0yYezJ2rgs5wKdkFxM0jQBI6rTEXDgA9n3oaOHUYvewQqoD0fcFk+R8M8j
            /mC7c7ckoeJa6fQKEapVuDNEgyf+htW/ixCfjmpLwssNkMdoR7FuIWW3s5iG0Lx2
            TxJcrC0vWNvv7K/SsOMhOac5r6voa6dN+iCZGULz0Wr2EBq+pPtRsteHpVfKXK4z
            ZvRtbOY/HR5qkr65uZtLhMvEiU3p/x4yJfW3Vdpbz9LgAeSxsVVt0PWWOYZg/abl
            TMTU4Y6X4DXg0+F72eDT4m9U6MrgeOVINKVar6TB/v9CVF68mJWZtoeFnoq9AY3W
            aTSwc2m5N+Dm5AchA768KqDWdEeMl2ttuwLioY/Ht+HkuwA=
            =xxeQ
            -----END PGP MESSAGE-----
        fp: 4C80959A5A0DC7D784CEDE1E1B7F34C12F7B86BE
    unencrypted_suffix: _unencrypted
    version: 3.6.1
